# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_order', '0002_auto_20181130_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_sn',
            field=models.CharField(max_length=64, unique=True, verbose_name='订单编号'),
        ),
    ]
