# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0003_auto_20181130_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsspu',
            options={'verbose_name': '商品SPU管理', 'verbose_name_plural': '商品SPU管理'},
        ),
    ]
