# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0004_auto_20181201_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsspu',
            options={'verbose_name': '商品SPU', 'verbose_name_plural': '商品SPU'},
        ),
    ]
